name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a medianoche UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    # Es una buena práctica definir los permisos que necesitará el job
    permissions: 
      contents: write # Necesario para hacer push a la rama 'output'

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: facu-caceres
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
          theme: pacman
          dark_theme: pacman-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          # La variable de entorno debe estar dentro del 'with' del mismo paso
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
