name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Pacman contribution graph
        uses: Platane/snk@v3
        with:
          # Verificá que tu usuario esté bien escrito aquí
          github_user_name: facu-caceres

          # Archivos de salida que se generarán
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg

          # ¡ESTA ES LA PARTE MÁS IMPORTANTE PARA TU PROBLEMA!
          # Asegurate de que estas dos líneas existan y estén escritas EXACTAMENTE así.
          # Esto le ordena a la acción usar la apariencia de Pac-Man.
          theme: pacman
          dark_theme: pacman-dark

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
